version: '3'
services: 
  mypythonapp:
    image: "my-python-app"
    ports: 
      - "5000:5000"
    links:
      - "myeventstore"
  myeventstore:
    image: "eventstore/eventstore"
    ports:
      - "1113:1113"
      - "2113:2113"
