apiVersion: v1
kind: Service
metadata:
  name: my-event-subscriber-svc
spec:
  selector:
    app: event-subscriber
  type: NodePort
  ports:
    - name: tcp1
      port: 5000
      targetPort: 5000
      nodePort: 32001
