apiVersion: v1
kind: Service
metadata:
  name: myeventstoresvc
spec:
  selector:
    app: eventstore
  type: NodePort
  ports:
    - name: tcp1
      port: 1113
      targetPort: 1113
      nodePort: 31113
      protocol: TCP
    - name: tcp2
      port: 2113
      targetPort: 2113
      nodePort: 32113
      protocol: TCP
