apiVersion: v1
kind: Service
metadata:
  name: my-event-publisher-svc
spec:
  selector:
    app: event-publisher
  type: NodePort
  ports:
    - name: tcp1
      port: 5000
      targetPort: 5000
      nodePort: 32000
